//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TCTourismEbookingEntities : DbContext
    {
        public TCTourismEbookingEntities()
            : base("name=TCTourismEbookingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TourismOrderOperateLog> TourismOrderOperateLogs { get; set; }
        public DbSet<TourismOriginFeedback> TourismOriginFeedbacks { get; set; }
        public DbSet<TourismOriginFeedbackOrder> TourismOriginFeedbackOrders { get; set; }
    }
}
