//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourismOriginFeedbackOrder
    {
        public long TOFOId { get; set; }
        public long TOFId { get; set; }
        public string TOFOOrderNumber { get; set; }
        public int TOFOLineId { get; set; }
        public string TOFOLineTitle { get; set; }
        public byte TOFODealStatus { get; set; }
        public System.DateTime TOFODealTime { get; set; }
        public int TOFOSupplierId { get; set; }
        public System.DateTime TOFOStartDate { get; set; }
        public byte TOFODataFlag { get; set; }
        public byte TOFOTravelType { get; set; }
        public string TOFOSupplierName { get; set; }
    }
}
