//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourismOriginFeedback
    {
        public long TOFId { get; set; }
        public string TOFFeedbackId { get; set; }
        public string TOFCustomerName { get; set; }
        public string TOFMobile { get; set; }
        public string TOFOtherContact { get; set; }
        public string TOFCustomerStatus { get; set; }
        public string TOFFeedbackSource { get; set; }
        public string TOFDepart { get; set; }
        public string TOFReasonLevel1 { get; set; }
        public string TOFReasonLevel2 { get; set; }
        public string TOFReasonLevel3 { get; set; }
        public string TOFOrderTotalAmount { get; set; }
        public string TOFUrgency { get; set; }
        public string TOFFeedbackContext { get; set; }
        public System.DateTime TOFUrgeTime { get; set; }
        public string TOFUrgeTimes { get; set; }
        public string TOFMemberId { get; set; }
        public string TOFIsPayBack { get; set; }
        public string TOFPayBackStatus { get; set; }
        public string TOFPayBackTotalAmount { get; set; }
        public string TOFHandler { get; set; }
        public string TOFCenter { get; set; }
        public string TOFFeedbackStatus { get; set; }
        public string TOFSatisfaction { get; set; }
        public System.DateTime TOFComplaintTime { get; set; }
        public byte TOFStatus { get; set; }
        public byte TOFDataFlag { get; set; }
    }
}
