//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourismOrderOperateLog
    {
        public long Id { get; set; }
        public string OperatorIP { get; set; }
        public byte OperatorType { get; set; }
        public string OperateContent { get; set; }
        public string Operation { get; set; }
        public System.DateTime OperateTime { get; set; }
        public string Operator { get; set; }
        public byte OperatorObject { get; set; }
        public int OperatorObjectId { get; set; }
        public byte OperatePlateform { get; set; }
    }
}
